### ISSUE TITLE
What exactly is the "diff" column in the sqlite db file?

### ISSUE THREAD

**Issue by anantmittal** [activityhistory/nbcomet#3]

**Comment by acrule** [comment]
I'll have to look at it to confirm, but if I remember correctly the diff column saves a compressed version of every cell whose contents changed (not just the diff in the cell, but the entire contents for that cell) as well as a record of which cells are deleted. From this, you should be able to reconstruct every state of the notebook.

**Comment by acrule** [comment]
To be more specific, the diff column is a pickled python dictionary that lists all the cells that have changed since the last action. The dictionary uses the random cell_ids that nbcomet assigns to each cell as the key, and the value is the entire contents of the cell.

**Comment by acrule** [comment]
To be more specific, the diff column is a pickled python dictionary that lists all the cells that have changed since the last action. The dictionary uses the random cell_ids that nbcomet assigns to each cell as the key, and the value is the entire contents of the cell.
